# Specify the Oracle database Testcontainers image
quarkus.datasource.devservices.image-name=gvenzl/oracle-xe:latest

# Configure Quarkus to use an existing Oracle database on your host
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@localhost:1521:XE
quarkus.datasource.username=my-user
quarkus.datasource.password=my-password

# Enable Dev Services for testing and container reuse
quarkus.datasource.devservices.enabled=true
quarkus.datasource.devservices.reuse-containers=true

# Add a global API prefix (e.g., `api/v1`)
quarkus.http.root-path=/api/v1
