# APPLICATION
quarkus.application.name = colladocs
quarkus.application.version = 1.0.0
quarkus.application.ui-header = Swagger UI

# BASE URL
quarkus.http.root-path=/api/v1

# LOGGING
quarkus.log.metrics.enabled = true
# ALL, CONFIG, FINE, FINER, FINEST, OFF, SEVERE, WARNING
quarkus.log.level = ALL

# PERFORMANCE
# enable when ready for speed
quarkus.native.enabled = false